[package]
name = "corgi-rs"
version = "0.2.2"
edition = "2024"
description = "Vehicle VIN decoding library based on NHTSA database for Rust"
keywords = ["nhtsa", "vin", "vehicles", "decoding"]
categories = ["automotive", "parsing", "encoding"]
license = "MIT"

[dependencies]
chrono = "0.4.43"
fst = "0.4.7"
memmap2 = "0.9.10"
rkyv = "0.8.15"
rayon = {version = "1.11.0", optional = true }
dirs = "6.0.0"

[build-dependencies]
dirs = "6.0.0"
fst = "0.4.7"
rkyv = "0.8.15"

[features]
default = ["parallel"]
parallel = ["rayon"]

[profile.release]
opt-level = 3
